#!/usr/bin/env bash

mysql -u root -p$MYSQL_ROOT_PASSWORD -e "\
  CREATE DATABASE IF NOT EXISTS \`$MYSQL_EMP_DIR_DB_NAME\`; \
  CREATE USER IF NOT EXISTS \`$MYSQL_EMP_DIR_DB_USER\`@'localhost'; \
  GRANT ALL ON \`$MYSQL_EMP_DIR_DB_NAME\`.* TO \`$MYSQL_EMP_DIR_DB_USER\`@'localhost' IDENTIFIED BY '$MYSQL_EMP_DIR_DB_PASS'; \
"
SOURCE="${BASH_SOURCE[0]}"
DIR="$( dirname "$SOURCE" )"
mysql -u root -p$MYSQL_ROOT_PASSWORD $MYSQL_EMP_DIR_DB_NAME < $DIR/init_emp_dir