#!/usr/bin/env bash

mysql -p$MYSQL_ROOT_PASSWORD -e "CREATE DATABASE IF NOT EXISTS \`$MYSQL_EMP_DIR_DB_NAME\`"
mysql -p$MYSQL_ROOT_PASSWORD -e "CREATE USER IF NOT EXISTS \`$MYSQL_EMP_DIR_DB_USER\`@'localhost'"
mysql -p$MYSQL_ROOT_PASSWORD -e "SET PASSWORD FOR \`$MYSQL_EMP_DIR_DB_USER\` = PASSWORD('$MYSQL_EMP_DIR_DB_PASS')"
mysql -p$MYSQL_ROOT_PASSWORD -e "GRANT ALL ON \`$MYSQL_EMP_DIR_DB_NAME\`.* TO \`$MYSQL_EMP_DIR_DB_USER\`@'localhost'"